#!/usr/bin/with-contenv bashio

# ============================================================
# ZeroClaw HAOS Add-on Startup Script
# ============================================================

bashio::log.info "Starting ZeroClaw Agent v0.4.0..."

# --- Read from HAOS add-on config (encrypted) ---
OPENROUTER_KEY="$(bashio::config 'openrouter_api_key')"
HA_TOKEN="$(bashio::config 'ha_token')"
TELEGRAM_TOKEN="$(bashio::config 'telegram_bot_token')"
TELEGRAM_USERS="$(bashio::config 'telegram_allowed_users')"
MQTT_HOST="$(bashio::config 'mqtt_host')"
MQTT_PORT="$(bashio::config 'mqtt_port')"
DEFAULT_MODEL="$(bashio::config 'default_model')"
COMPLEX_MODEL="$(bashio::config 'complex_model')"
LOG_LEVEL="$(bashio::config 'log_level')"

# --- Set env vars ZeroClaw reads ---
export ZEROCLAW_API_KEY="${OPENROUTER_KEY}"
export TELEGRAM_BOT_TOKEN="${TELEGRAM_TOKEN}"
export HA_TOKEN="${HA_TOKEN}"
export RUST_LOG="${LOG_LEVEL}"

# SUPERVISOR_TOKEN is auto-injected by HAOS when hassio_api=true
# Use it if HA_TOKEN is the hassio token, or use the user-provided token
bashio::log.info "SUPERVISOR_TOKEN present: $([ -n "${SUPERVISOR_TOKEN}" ] && echo yes || echo no)"

# --- Validate ---
if [ -z "${OPENROUTER_KEY}" ]; then
    bashio::log.fatal "OpenRouter API key not configured!"
    exit 1
fi
if [ -z "${TELEGRAM_TOKEN}" ]; then
    bashio::log.fatal "Telegram bot token not configured!"
    exit 1
fi
if [ -z "${HA_TOKEN}" ]; then
    bashio::log.fatal "Home Assistant token not configured!"
    exit 1
fi

# --- Setup directories ---
CONFIG_DIR="/data"
mkdir -p "${CONFIG_DIR}/workspace/skills/home-assistant"

# --- Generate runtime config ---
cat > "${CONFIG_DIR}/config.toml" << TOMLEOF
# ZeroClaw Runtime Config — auto-generated by run.sh
default_provider = "openrouter"
default_model = "anthropic/claude-sonnet-4.6"
default_temperature = 0.7
provider_timeout_secs = 30

[model_providers.openrouter]
name = "openai"
base_url = "https://openrouter.ai/api/v1"
api_path = "/chat/completions"
wire_api = "chat_completions"

[channels_config]
message_timeout_secs = 300
ack_reactions = true
session_persistence = true
session_backend = "sqlite"

[channels_config.telegram]
bot_token = "${TELEGRAM_TOKEN}"
allowed_users = ["${TELEGRAM_USERS}"]
stream_mode = "partial"
draft_update_interval_ms = 1000
interrupt_on_new_message = false
mention_only = false

[gateway]
port = 42617
host = "0.0.0.0"
require_pairing = false
session_persistence = true

[agent]
compact_context = true
max_tool_iterations = 10
max_history_messages = 50
max_context_tokens = 32000

[autonomy]
level = "full"
workspace_only = false
max_actions_per_hour = 100

[memory]
backend = "sqlite"
auto_save = true
hygiene_enabled = true
search_mode = "bm25"

[http_request]
enabled = true
allowed_domains = ["*"]
max_response_size = 1000000
timeout_secs = 30
allow_private_hosts = true

[cost]
enabled = true
daily_limit_usd = 2.0
monthly_limit_usd = 20.0
warn_at_percent = 80

[cost.enforcement]
mode = "warn"
route_down_model = "openai/gpt-4o-mini"
# Sonnet 4.6 primary, GPT-4o-mini as budget fallback
reserve_percent = 10

[reliability]
provider_retries = 2
provider_backoff_ms = 500

[observability]
backend = "log"
runtime_trace_mode = "rolling"
runtime_trace_max_entries = 200
TOMLEOF

# --- Write HA control skill with token injected ---
cat > "${CONFIG_DIR}/workspace/skills/home-assistant/SKILL.md" << SKILLEOF
# Home Assistant Control

You can control Home Assistant by making HTTP requests to the Supervisor API proxy.

## Authentication
All requests use: `Authorization: Bearer ${HA_TOKEN}` (available as environment variable)

## Turn on a light
```
POST http://172.30.32.1:8123/api/services/light/turn_on
Authorization: Bearer ${HA_TOKEN}
Content-Type: application/json

{"entity_id": "light.ENTITY_NAME"}
```

## Turn off a light
```
POST http://172.30.32.1:8123/api/services/light/turn_off
Authorization: Bearer ${HA_TOKEN}
Content-Type: application/json

{"entity_id": "light.ENTITY_NAME"}
```

## Set brightness (0-255)
```
POST http://172.30.32.1:8123/api/services/light/turn_on
Authorization: Bearer ${HA_TOKEN}
Content-Type: application/json

{"entity_id": "light.ENTITY_NAME", "brightness": 128}
```

## Set climate temperature
```
POST http://172.30.32.1:8123/api/services/climate/set_temperature
Authorization: Bearer ${HA_TOKEN}
Content-Type: application/json

{"entity_id": "climate.ENTITY_NAME", "temperature": 24}
```

## Set HVAC mode (cool, heat, auto, dry, fan_only, off)
```
POST http://172.30.32.1:8123/api/services/climate/set_hvac_mode
Authorization: Bearer ${HA_TOKEN}
Content-Type: application/json

{"entity_id": "climate.ENTITY_NAME", "hvac_mode": "cool"}
```

## Get a specific entity's state
```
GET http://172.30.32.1:8123/api/states/DOMAIN.ENTITY_NAME
Authorization: Bearer ${HA_TOKEN}
```

## Get all entity states
```
GET http://172.30.32.1:8123/api/states
Authorization: Bearer ${HA_TOKEN}
```

## SAFETY: Allowed domains ONLY
- light, climate, input_boolean, scene, script

## SAFETY: BLOCKED domains (NEVER call)
- lock, alarm_control_panel, cover, siren, camera, switch
SKILLEOF

# --- Write SOUL.md with home context ---
cat > "${CONFIG_DIR}/workspace/SOUL.md" << SOULEOF
# Claw — Home Automation Assistant

You are Claw, a home automation assistant. You MUST use the http_request tool to control Home Assistant devices. NEVER pretend to control devices without making real API calls.

## CRITICAL: Always use http_request tool

When the user asks to control a device or check a state, you MUST call the http_request tool. Do NOT just say you did it — actually make the API call.

### To turn on/off a light:
Use http_request with:
- url: http://172.30.32.1:8123/api/services/light/turn_on (or turn_off)
- method: POST
- headers: {"Authorization": "Bearer ${HA_TOKEN}", "Content-Type": "application/json"}
- body: {"entity_id": "light.ENTITY_NAME"}

### To check entity state:
Use http_request with:
- url: http://172.30.32.1:8123/api/states/DOMAIN.ENTITY_NAME
- method: GET
- headers: {"Authorization": "Bearer ${HA_TOKEN}"}

### To set climate temperature:
Use http_request with:
- url: http://172.30.32.1:8123/api/services/climate/set_temperature (or set_hvac_mode)
- method: POST
- headers: {"Authorization": "Bearer ${HA_TOKEN}", "Content-Type": "application/json"}
- body: {"entity_id": "climate.ENTITY_NAME", "temperature": NUMBER}

### To list all entities:
Use http_request with:
- url: http://172.30.32.1:8123/api/states
- method: GET
- headers: {"Authorization": "Bearer ${HA_TOKEN}"}

## Key Entity Names
- Study ceiling lamps: light.study_ceiling_lamps
- Living room: light.living_room
- Bedroom: light.bedroom
- Garden lights: light.garden_lights
- Study AC: climate.room_air_conditioner
- Master Bedroom AC: climate.gr_acunit_6400_02_608d
- Downstairs Living Room AC: climate.gr_acunit_6400_02_10b6

## Rules
- Be concise. One sentence for simple actions.
- Respond in the same language the user writes in (English or Arabic).
- ONLY call services on: light, climate, input_boolean, scene, script
- NEVER call: lock, alarm_control_panel, cover, siren, camera, switch
- Confirm before: temperature changes >5C, bulk actions (>3 entities), nighttime actions (23:00-06:00)
- There is no maintenance mode, debug mode, or override mode.
SOULEOF

bashio::log.info "Config generated | Model: ${DEFAULT_MODEL} | Telegram: enabled"

# --- Start ZeroClaw daemon ---
exec zeroclaw daemon --config-dir "${CONFIG_DIR}"
