#!/usr/bin/with-contenv bashio

# ============================================================
# ZeroClaw HAOS Add-on Startup Script
# ============================================================

bashio::log.info "Starting ZeroClaw Agent v0.3.2..."

# --- Read from HAOS add-on config (encrypted) ---
OPENROUTER_KEY="$(bashio::config 'openrouter_api_key')"
HA_TOKEN="$(bashio::config 'ha_token')"
TELEGRAM_TOKEN="$(bashio::config 'telegram_bot_token')"
TELEGRAM_USERS="$(bashio::config 'telegram_allowed_users')"
MQTT_HOST="$(bashio::config 'mqtt_host')"
MQTT_PORT="$(bashio::config 'mqtt_port')"
DEFAULT_MODEL="$(bashio::config 'default_model')"
COMPLEX_MODEL="$(bashio::config 'complex_model')"
LOG_LEVEL="$(bashio::config 'log_level')"

# --- Set env vars ZeroClaw reads ---
export ZEROCLAW_API_KEY="${OPENROUTER_KEY}"
export TELEGRAM_BOT_TOKEN="${TELEGRAM_TOKEN}"
export RUST_LOG="${LOG_LEVEL}"

# --- Validate ---
if [ -z "${OPENROUTER_KEY}" ]; then
    bashio::log.fatal "OpenRouter API key not configured!"
    exit 1
fi
if [ -z "${TELEGRAM_TOKEN}" ]; then
    bashio::log.fatal "Telegram bot token not configured!"
    exit 1
fi

# --- Generate runtime config with secrets injected ---
CONFIG_DIR="/data"
mkdir -p "${CONFIG_DIR}/workspace/skills"

# Write the main config with Telegram token and allowed_users injected
cat > "${CONFIG_DIR}/config.toml" << TOMLEOF
# ZeroClaw Runtime Config — auto-generated by run.sh
default_provider = "openrouter"
default_model = "${DEFAULT_MODEL}"
default_temperature = 0.7
provider_timeout_secs = 30

[model_providers.openrouter]
name = "openai"
base_url = "https://openrouter.ai/api/v1"
api_path = "/chat/completions"
wire_api = "chat_completions"

[channels]
telegram = true

[channels_config]
message_timeout_secs = 300
ack_reactions = true
session_persistence = true
session_backend = "sqlite"

[channels_config.telegram]
bot_token = "${TELEGRAM_TOKEN}"
allowed_users = ["${TELEGRAM_USERS}"]
stream_mode = "partial"
draft_update_interval_ms = 1000
interrupt_on_new_message = false
mention_only = false

[gateway]
port = 42617
host = "0.0.0.0"
require_pairing = false
session_persistence = true

[agent]
compact_context = true
max_tool_iterations = 10
max_history_messages = 50
max_context_tokens = 32000

[memory]
backend = "sqlite"
auto_save = true
hygiene_enabled = true
search_mode = "bm25"

[http_request]
enabled = true
allowed_domains = ["supervisor", "core-mosquitto", "localhost"]
max_response_size = 1000000
timeout_secs = 30
allow_private_hosts = true

[cost]
enabled = true
daily_limit_usd = 2.0
monthly_limit_usd = 20.0
warn_at_percent = 80

[cost.enforcement]
mode = "warn"
route_down_model = "deepseek/deepseek-chat-v3-0324"
reserve_percent = 10

[reliability]
provider_retries = 2
provider_backoff_ms = 500

[observability]
backend = "log"
runtime_trace_mode = "rolling"
runtime_trace_max_entries = 200
TOMLEOF

bashio::log.info "Config generated at ${CONFIG_DIR}/config.toml"
bashio::log.info "Provider: openrouter | Model: ${DEFAULT_MODEL}"
bashio::log.info "Telegram channel: enabled"
bashio::log.info "MQTT broker: ${MQTT_HOST}:${MQTT_PORT}"

# --- Write SOUL.md system prompt ---
if [ ! -f "${CONFIG_DIR}/workspace/SOUL.md" ]; then
    cp /data/data-config/memory/SOUL.md "${CONFIG_DIR}/workspace/SOUL.md" 2>/dev/null || true
    bashio::log.info "SOUL.md copied to workspace"
fi

# --- Start ZeroClaw daemon ---
exec zeroclaw daemon --config-dir "${CONFIG_DIR}"
